$axure.loadDocument({
  "configuration":{
    "showPageNotes":true,
    "showPageNoteNames":false,
    "showAnnotations":true,
    "linkStyle":"b",
    "linkFlowsToPages":true,
    "linkFlowsToPagesNewWindow":true,
    "hideAddress":false,
    "preventScroll":false,
    "useLabels":false,
    "enabledViewIds":[],
    "loadFeedbackPlugin":false},
  "sitemap":{
    "rootNodes":[{
        "pageName":"V0.3",
        "type":"Wireframe",
        "url":"v0_3.html",
        "children":[{
            "pageName":"amazon",
            "type":"Wireframe",
            "url":"amazon.html"}]},
{
        "pageName":"支持转运公司",
        "type":"Wireframe",
        "url":"支持转运公司.html",
        "children":[{
            "pageName":"提交商品网址",
            "type":"Wireframe",
            "url":"提交商品网址.html"},
{
            "pageName":"确认订单2",
            "type":"Wireframe",
            "url":"确认订单2.html"},
{
            "pageName":"支付费用",
            "type":"Wireframe",
            "url":"支付费用.html"},
{
            "pageName":"国际物流",
            "type":"Wireframe",
            "url":"国际物流.html"},
{
            "pageName":"确认收货",
            "type":"Wireframe",
            "url":"确认收货.html"}]},
{
        "pageName":"不支持转运公司",
        "type":"Wireframe",
        "url":"不支持转运公司.html",
        "children":[{
            "pageName":"提交网址",
            "type":"Wireframe",
            "url":"提交网址.html"},
{
            "pageName":"寻找帮手",
            "type":"Wireframe",
            "url":"寻找帮手.html"},
{
            "pageName":"支付费用",
            "type":"Wireframe",
            "url":"支付费用_1.html"}]},
{
        "pageName":"无链接",
        "type":"Wireframe",
        "url":"无链接.html",
        "children":[{
            "pageName":"发布需求",
            "type":"Wireframe",
            "url":"发布需求.html"},
{
            "pageName":"提交订单",
            "type":"Wireframe",
            "url":"提交订单.html"},
{
            "pageName":"选择买手",
            "type":"Wireframe",
            "url":"选择买手.html"},
{
            "pageName":"支付费用",
            "type":"Wireframe",
            "url":"支付费用_2.html"},
{
            "pageName":"买手购买",
            "type":"Wireframe",
            "url":"买手购买.html"},
{
            "pageName":"买手发货",
            "type":"Wireframe",
            "url":"买手发货.html"},
{
            "pageName":"确认收货",
            "type":"Wireframe",
            "url":"确认收货_1.html"}]},
{
        "pageName":"买手抢单",
        "type":"Wireframe",
        "url":"买手抢单.html",
        "children":[{
            "pageName":"提交佣金方案",
            "type":"Wireframe",
            "url":"提交佣金方案.html"},
{
            "pageName":"等待确认",
            "type":"Wireframe",
            "url":"等待确认.html"},
{
            "pageName":"已确认",
            "type":"Wireframe",
            "url":"已确认.html"},
{
            "pageName":"已经完成",
            "type":"Wireframe",
            "url":"已经完成.html"}]},
{
        "pageName":"V0.9index",
        "type":"Wireframe",
        "url":"v0_9index.html",
        "children":[{
            "pageName":"提交商品网址",
            "type":"Wireframe",
            "url":"提交商品网址_1.html"},
{
            "pageName":"New Page 1",
            "type":"Wireframe",
            "url":"new_page_1.html"}]}]},
  "globalVariables":{
    "onloadvariable":""},
  "defaultAdaptiveView":{
    "name":"",
    "size":{
      "width":0,
      "height":0},
    "condition":"<="},
  "adaptiveViews":[],
  "stylesheet":{
    "defaultStyles":{
      "buttonShape":{
        "id":"a61f1d97a7984d01842d9da8f3bb7042",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "paragraph":{
        "id":"df6cf2c3e80e4a00af62c37ce99e888f",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"20px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h1":{
        "id":"5d33b2706d424b43a2ecb3cb711bb0fa",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"32px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"20px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h2":{
        "id":"750c5c3283e4411bb26f765cc709f3e4",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"24px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h3":{
        "id":"ba8dd0db7ba1414aa01c2047f8d5d7c3",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"18px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h4":{
        "id":"9747259d6de541a08105847ac9b9d35f",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"14px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h5":{
        "id":"1b98c12428004978a25c3ca7920ac27c",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "h6":{
        "id":"2a54f6ae1f7c4ba6a81d66c704811e26",
        "fontName":"'Arial Bold', 'Arial'",
        "fontSize":"10px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "imageBox":{
        "id":"68f0a199bf1b4fd5aa6df4584cec0767",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "hyperlink":{
        "id":"5e9426727a944a06b918d9df8eae43d8",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF0000FF,
          "opacity":1},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false},
      "hyperlinkMouseOver":{
        "id":"fdef218d30ae4497aee6820d22751519",
        "underline":true},
      "hyperlinkMouseDown":{
        "id":"6bff2655d0f24a298cb96a7c72e9a5a2"},
      "textBox":{
        "id":"431c2ac9c1fa4f49aaff65e04678c9bd",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "textArea":{
        "id":"aaa84d4c30a745888064e847d97d24d2",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "comboBox":{
        "id":"93283d757bef4401840c005d315228ac",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "listBox":{
        "id":"c6eb26d0429a4c8e82bdca5a0dcf20e3",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "checkbox":{
        "id":"c5dd189265114bae94e026bce74d6d10",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "radioButton":{
        "id":"37163d72f23645469dca41bc8d5efe8b",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "flowShape":{
        "id":"f532373bf33c46908222bbfeb8e62d5b",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"linearGradient",
          "colors":[{
              "color":0xFFFFFFFF},
{
              "color":0xFFF2F2F2},
{
              "color":0xFFE4E4E4},
{
              "color":0xFFFFFFFF}]},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "treeNodeObject":{
        "id":"9c667a6fe05c459ebff569508e9858e3",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid"},
      "button":{
        "id":"5e6a814ba8444a7ab3de398ce0082048",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "imageMapRegion":{
        "id":"243e904daca7472e85bb7a061c55a36a",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0"},
      "inlineFrame":{
        "id":"3c67d7ddcb3c453f83f24e228ce9e0e9",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "dynamicPanel":{
        "id":"d1baf37b4bfb4b8aae78e7038ab5f09b",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "referenceDiagramObject":{
        "id":"1cc110e226ef4e179299e675c7b7baf4",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "repeater":{
        "id":"042ea3cf4b154b19852a78e69380189d",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.34901961684227}}},
      "table":{
        "id":"3abee1f7701a4c53908629371b976c58",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "tableCell":{
        "id":"9074695981f941ee9de82b0b0303ca47",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058844566345}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "menuObject":{
        "id":"3ea84b64e4c64bdc8d95412f96062a42",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "horizontalLine":{
        "id":"6165129ca1684a6eab4d5840ce4fd755",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "opacity":"1",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF000000},
        "linePattern":"solid"},
      "verticalLine":{
        "id":"dcf1fc4a40bf4f6bb384997ecb3f9a06",
        "fontName":"'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "opacity":"1",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF000000},
        "linePattern":"solid"},
      "connector":{
        "id":"e606f9ae76ea422f97c517eae3bec015",
        "fontName":"'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF0099CC},
        "linePattern":"solid"}},
    "customStyles":{
}}});